import { supportedSignAlg } from '../tools/alg';
import { baseUrl } from '../tools/url';
import * as pkg from '../../../package.json';

export default async () => Object({
  issuer: baseUrl,
  authorization_endpoint: `${baseUrl}/auth/authorize`,
  token_endpoint: `${baseUrl}/auth/token`,
  token_endpoint_auth_methods_supported: ['client_secret_basic'],
  token_endpoint_auth_signing_alg_values_supported: ['RS256', 'ES256'],
  userinfo_endpoint: `${baseUrl}/auth/userinfo`,
  check_session_iframe: `${baseUrl}/auth/check_session`,
  end_session_endpoint: `${baseUrl}/auth/end_session`,
  jwks_uri: `${baseUrl}/.well-known/jwks.json`,
  registration_endpoint: `${baseUrl}/auth/register`,
  response_modes_supported: ['query', 'fragment'],
  grant_types_supported: ['authorization_code', 'implicit'],
  scopes_supported: [
    'openid',
    'profile',
    'email',
    'address',
    'phone',
    'offline_access',
  ],
  response_types_supported: [
    'code',
    'code id_token',
    'id_token',
    'token id_token',
  ],
  subject_types_supported: ['public', 'pairwise'],
  userinfo_signing_alg_values_supported: await supportedSignAlg(),
  id_token_signing_alg_values_supported: await supportedSignAlg(),
  request_object_signing_alg_values_supported: await supportedSignAlg(),
  display_values_supported: ['page', 'popup'],
  claim_types_supported: ['normal', 'distributed'],
  claims_supported: [
    'sub',
    'iss',
    'auth_time',
    'acr',
    'name',
    'given_name',
    'family_name',
    'nickname',
    'profile',
    'picture',
    'website',
    'email',
    'email_verified',
    'locale',
    'zoneinfo',
  ],
  claims_parameter_supported: true,
  service_documentation: pkg.homepage,
  ui_locales_supported: ['en-US', 'en-GB', 'de-DE', 'de-AT'],
});
