version: '3'

services:
  db:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: p4ssw0rD
    image: mongo:3-stretch
    networks:
      - mongo-net
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo:/data/db
  koa-oidc-provider:
    build: 
      args:
        DEBUG: error:*
        MONGO_HOST: db
        MONGO_PASSWORD: p4ssw0rD
        MONGO_USER: admin
        REDIS_HOST: redis
      context: .
    depends_on:
      - db
      - redis
    dns: 8.8.8.8
    image: koa-oidc-provider
    networks:
      - mongo-net
      - redis-net
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./private:/usr/src/oidc/private
  redis:
    image: redis:5-alpine
    networks:
      - redis-net
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis:/data

networks:
  mongo-net:
  redis-net: